name: AL-TASK Auth
values:
  - key: baseUrl
    value: 'http://localhost:5512'
  - key: testEmail
    value: testuser@example.com
  - key: testPassword
    value: Test@1234
  - key: userAccount
    value: ''
  - key: userPassword
    value: ''
  - key: accessToken
    value: ''
  - key: refreshToken
    value: ''
  - key: userId
    value: ''
  - key: resetToken
    value: ''
  - key: resetGrant
    value: ''
  - key: testemailverification
    value: ''
  - key: passEmailVerification
    value: ''
