export const AUTH_ERROR_CODES = {
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  TOKEN_FAMILY_REVOKED: 'TOKEN_FAMILY_REVOKED',
} as const;

export type AuthErrorCodeLiteral = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
